##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.7.0-B52] date: [Tue Dec 09 17:16:44 CST 2025] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------
SHELL = cmd.exe
######################################
# target
######################################
TARGET = red_only


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/dcmi.c \
Core/Src/i2c.c \
Core/Src/spi.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/usb_otg.c \
Core/Src/stm32u5xx_it.c \
Core/Src/stm32u5xx_hal_msp.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_cortex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_dcmi.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_dma.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_dma_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_i2c.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_i2c_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rcc.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rcc_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_flash.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_flash_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_gpio.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_exti.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_pwr.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_pwr_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_gtzc.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_icache.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_spi.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_spi_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_tim.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_tim_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_uart.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_uart_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_pcd.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_pcd_ex.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_ll_usb.c \
Core/Src/system_stm32u5xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Lora/lora.c \
TINYC256_192/data_rw.c \
TINYC256_192/falcon_cmd.c \
TINYC256_192/tinyAdjust.c \
TINYC256_192/vdcmd.c \
TINYC256_192/tinycTask.c \
Core/Src/gpdma.c \
Middlewares/ST/usbx/common/core/src/ux_system_tasks_run.c \
Middlewares/ST/usbx/common/core/src/ux_utility_debug_callback_register.c \
Middlewares/ST/usbx/common/core/src/ux_utility_debug_log.c \
Middlewares/ST/usbx/common/core/src/ux_utility_delay_ms.c \
Middlewares/ST/usbx/common/core/src/ux_utility_descriptor_pack.c \
Middlewares/ST/usbx/common/core/src/ux_utility_descriptor_parse.c \
Middlewares/ST/usbx/common/core/src/ux_utility_error_callback_register.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_get_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_put.c \
Middlewares/ST/usbx/common/core/src/ux_utility_long_put_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_add_safe.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_mulc_safe.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_allocate_mulv_safe.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_compare.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_copy.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_free.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_byte_pool_create.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_byte_pool_search.c \
Middlewares/ST/usbx/common/core/src/ux_utility_memory_set.c \
Middlewares/ST/usbx/common/core/src/ux_utility_physical_address.c \
Middlewares/ST/usbx/common/core/src/ux_utility_set_interrupt_handler.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_get_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_put.c \
Middlewares/ST/usbx/common/core/src/ux_utility_short_put_big_endian.c \
Middlewares/ST/usbx/common/core/src/ux_utility_string_length_check.c \
Middlewares/ST/usbx/common/core/src/ux_utility_string_length_get.c \
Middlewares/ST/usbx/common/core/src/ux_utility_string_to_unicode.c \
Middlewares/ST/usbx/common/core/src/ux_utility_unicode_to_string.c \
Middlewares/ST/usbx/common/core/src/ux_utility_virtual_address.c \
Middlewares/ST/usbx/common/core/src/ux_system_error_handler.c \
Middlewares/ST/usbx/common/core/src/ux_system_initialize.c \
Middlewares/ST/usbx/common/core/src/ux_system_uninitialize.c \
FLASH/spif.c \
LCD/st7789.c \
LCD/fonts.c \
lib/utils.c \
Core/Src/rtc.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rtc.c \
Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rtc_ex.c

# ASM sources
ASM_SOURCES =  \
startup_stm32u575xx.s

# ASMM sources
ASMM_SOURCES = 

# ASMMC sources
ASMMC_SOURCE = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m33

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32U575xx \
-DUX_INCLUDE_USER_DEFINE_FILE


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32U5xx_HAL_Driver/Inc \
-IDrivers/STM32U5xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32U5xx/Include \
-IDrivers/CMSIS/Include \
-ILora \
-ITINYC256_192 \
-IUSBX/App \
-IUSBX/Target \
-IMiddlewares/ST/usbx/common/core/inc \
-IMiddlewares/ST/usbx/ports/generic/inc \
-IFLASH \
-ILCD \
-Ilib


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32U575xx_FLASH.ld

# libraries
LIBS = -lc -lm
LIBDIR = -LTINYC256_192
LIBFILES = TINYC256_192/libirtemp.lib
LDFLAGS = $(MCU)  -T$(LDSCRIPT) $(LIBDIR) $(LIBS) $(LIBFILES) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMMC_SOURCES:.c=.o)))
vpath %.S $(sort $(dir $(ASMMC_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
